name: Docker meteormail Image CI

on:
  workflow_dispatch:  # 仅支持手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timestamp tag
        id: timestamp
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image for amd64 and arm64
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ldxw/meteormail:latest \
            -t ldxw/meteormail:${{ steps.timestamp.outputs.tag }} \
            -t ghcr.io/${{ github.repository_owner }}/meteormail:latest \
            -t ghcr.io/${{ github.repository_owner }}/meteormail:${{ steps.timestamp.outputs.tag }} \
            . --push