name: Docker meteormail Image CI

on:
  workflow_dispatch:  # 仅支持手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timestamp tag
        id: timestamp
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image for amd64 and arm64
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ldxw/meteormail:latest \
            -t ldxw/meteormail:${{ steps.timestamp.outputs.tag }} \
            -t ghcr.io/${{ github.repository_owner }}/meteormail:latest \
            -t ghcr.io/${{ github.repository_owner }}/meteormail:${{ steps.timestamp.outputs.tag }} \
            . --push

      - name: Push README.md to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: ldxw/meteormail
        run: |
          # 获取 Docker Hub API 的 token
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'"$DOCKERHUB_USERNAME"'", "password": "'"$DOCKERHUB_PASSWORD"'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)

          # 读取 README.md 文件内容
          README=$(cat README.md)

          # 更新 Docker Hub 仓库的描述
          curl -s -o /dev/null -w "%{http_code}\n" -H "Authorization: JWT $TOKEN" -H "Content-Type: application/json" -X PATCH -d '{"full_description": "'"${README//$'\n'/\\n}"'"}' "https://hub.docker.com/v2/repositories/$DOCKERHUB_REPO/"